### ISSUE TITLE
History box

### ISSUE THREAD

**Issue by slvstr1** [ECON3/dAuction2_interactive3#12]
History box is so far only visible for retailer and not for producer

**Comment by janvavra** [comment]
There is no history box for producer in screen design.
Partially implemented.
I assume that penalty, units required and units obtained will be not present for producer. What columns will be present for him?

**Comment by slvstr1** [comment]
These elements
Period	Profit	Units sold         cost		Trading result

**Comment by janvavra** [comment]
units sold are not present in player_stats, yet

**Comment by slvstr1** [comment]
player_stats.units_obtained is for retailer net number of units bought and for producer net number of units sold

**Comment by slvstr1** [comment]
No historybox yet in stage 2

**Comment by janvavra** [comment]
should be OK now
