### ISSUE TITLE
Implement NEXT button in distrib App

### ISSUE THREAD

**Issue by janvavra** [ECON3/dAuction2_interactive3#18]
Clicking next button in distrib app, player should go to some url, that will send him to "lobby" where he will wait for experiment to begin.

**Comment by slvstr1** [comment]
Use this link: <a href="{% url "DISTRIBUTION-contin" %}">
It parks the player in the page "wait"

url(r'contin', views.contin, name='DISTRIBUTION-contin')

**Comment by janvavra** [comment]
done

**Comment by slvstr1** [comment]
Can you add to the waiting page "wait.html" the ajax check for refresh?
Once the MASTER says to go to a next stage he will move there by himself as long as he refreshes.

**Comment by janvavra** [comment]
sure, will do

**Comment by janvavra** [comment]
done again
