### ISSUE TITLE
MASTER/templates/MASTER/failed_to_create_player.html

### ISSUE THREAD

**Issue by slvstr1** [ECON3/dAuction2_interactive3#29]
Subjects that end up on the MASTER/templates/MASTER/failed_to_create_player.html should still get a refresh check.

Not quite sure why it doesnt work now - the template extends the base where the refresh function is written in.

**Comment by janvavra** [comment]
Refresh function needs jQuerry to run. Im pretty sure that jQuerry is not included properly in base. Will look at it.

**Comment by janvavra** [comment]
Refresh code is working on the page.
What should this page do and how do I get there from players side?

**Comment by slvstr1** [comment]
player gets there if he logs on after the MASTER has already created the draws

**Comment by slvstr1** [comment]
He doesnt need to do much, but to check for the refresh, so that once recreate players has been chosen by the MASTER, he refreshes automatically.

**Comment by slvstr1** [comment]
If I open the developer tools on the page MASTER/templates/MASTER/failed_to_create_player.html, I do not see a refresh call

**Comment by janvavra** [comment]
Fixed. You broke it by adding 
![image](https://cloud.githubusercontent.com/assets/12901263/14263173/679e49ba-fab9-11e5-8783-33291c61ddc7.png) into JS code but not defining auction model to be passed on template in views :cat2:  :cat2: :cat2:
