### ISSUE TITLE
MAster view

### ISSUE THREAD

**Issue by slvstr1** [ECON3/dAuction2_interactive3#33]
Master should see it if a player closes chrome

**Comment by slvstr1** [comment]
There is the field user.state= models.CharField(max_length=125, default="loggedin")
Could you add to the refresh checker that if the refresh gets no respons, he sets user.state="No resp"?

(that should suffice to close this issue)

**Comment by janvavra** [comment]
I will implement it in this way:
Make user refresh call log time of connection to new database field in user db. Then ajax_admin call will compare this field with current time, and if current_time-time_last_refreshcheck > 5 seconds it sets user.state to "NO resp", otherwise to "loggedin".

**Comment by slvstr1** [comment]
Sounds good. Could you just for otherwise leave the user.state unchanged? (because I use user.state also to store other possible states in).

**Comment by janvavra** [comment]
I can, but it will not refresh to "loggedin" if user reconnects. 
I can add a condition, that only if user.state="NO resp" change it to "loggedin". Or it can be solved in some another way, depending on your intentions with user.state.

**Comment by slvstr1** [comment]
Ok, that seems the best way to me (add a condition, that only if user.state="NO resp" change it to "loggedin").

**Comment by slvstr1** [comment]
Hold that thought. How about this. I made a var, Players.last_alive. Just set last_alive = int(current_time-time_last_refreshcheck )

**Comment by janvavra** [comment]
Implemented in slightly different way.
Players refresh call updates player.last_refresh_date to date of refresh.
Admins admin_ajax call then calculates timezone.now() - player.last_refresh_date and sets it as player.last_alive.
