### ISSUE TITLE
Rewrite/review ajax_admin

### ISSUE THREAD

**Issue by janvavra** [ECON3/dAuction2_interactive3#40]
There are remnants of code in master.ajax_admin that does not belong here and will not work on Celery.
What ajax_admin should do only to run periodically operations on database tables like:

- pushing the timer (setting it to time_now - time_end)
- actualizing last online time for users
- moving market to another round when some conditions are met, etc.
- if there is logged user with no player, create player for him
- ...etc.

Lot is already programmed here, but its kinda messy, because ajax_admin served as a view that produced some pages originally.

**Comment by slvstr1** [comment]
Not quite clear to me. I thought that all the tasks you mention will be done by celery. Maybe discuss on Tuesday

**Comment by janvavra** [comment]
They will, but they need to be rewritten in some more clear form then is now present in ajax_admin. You can rewrite current ajax_admin and then I will just copy it to Celery.
We can discuss on Tuesday for sure.

**Comment by janvavra** [comment]
Destroyed and recreated vagrant box and it works for me, strange.

**Comment by janvavra** [comment]
For example:


    if request.user.username=='admin':
        player_list = Player.objects.all().order_by('pk')
        # form = NumberForm(initial={'PR_number':auction.PR_number,})
        # form2 = NumberForm(initial={'instruction_totalPages': auction.instruction_totalPages,'time_for_forward':auction.time_for_forward, 'time_for_forward_waiting_after':auction.time_for_forward_waiting_after,'time_for_spot': auction.time_for_spot,'time_for_spot_waiting_after':auction.time_for_spot_waiting_after, 'total_periods':auction.total_periods})

        tmpl='MASTER/master.html'


Will be obsolete, because there will be no request.user.username or tmpl='MASTER/master.html' needed on celery. And is also not needed now.

**Comment by slvstr1** [comment]
I see what you mean. Have a look. I now mostly commented out. Will make formatting bit better in second round.
