### ISSUE TITLE
delete & recreate and refresh all players dont work. 

### ISSUE THREAD

**Issue by slvstr1** [ECON3/dAuction2_interactive3#41]
delete & recreate and refresh all players dont work. Figure out why and solve it.

**Comment by slvstr1** [comment]
I programmed something that relies on the refresh check on all users, including the admin. But there seems to be no refresh ajax for the MASTERS view anymore. It doesnt refresh if I request and if I open dev tool I see there is no ask for refresh. This is odd, because I believe it used to be there.

Can you put the check for MASTERS for refreshing back? You can maybe also ajaxify it into the master, but that seems a bit like a lot of work to me.

PS: remember that the refresh property is now on the user, not on the player anymore. A pagerefresh should thus occur when user.refresh_now==True

**Comment by janvavra** [comment]
I will look at it. I removed it few commits back, because it was broken for master thanks to user extension (or it looked broken from the log).

**Comment by janvavra** [comment]
Should work now
